crazyflies: 
  - id: 1
    channel: 80
    initialPosition: [-1.0, 1.0, 0.0]
    type: default
  - id: 2
    channel: 80
    initialPosition: [0.0, 1.0, 0.0]
    type: default
  - id: 3
    channel: 80
    initialPosition: [1.0, 1.0, 0.0]
    type: default
  - id: 4
    channel: 80
    initialPosition: [-1.0, 0.0, 0.0]
    type: default
  - id: 5
    channel: 80
    initialPosition: [0.0, 0.0, 0.0]
    type: default
  - id: 6
    channel: 80
    initialPosition: [1.0, 0.0, 0.0]
    type: default
  - id: 7
    channel: 80
    initialPosition: [-1.0, -1.0, 0.0]
    type: default
  - id: 8
    channel: 80
    initialPosition: [0.0, -1.0, 0.0]
    type: default
  - id: 9
    channel: 80
    initialPosition: [1.0, -1.0, 0.0]
    type: default
  - id: 10
    channel: 80
    initialPosition: [2.0, 1.0, 0.0]
    type: default